version: '3'

services:
    web:
        build: .
        command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 4
        volumes:
            - .:/code
        ports:
            - 8000:8000

#         depends_on:
#             - db
#         links:
#             - db
#     db:
#         image: postgres
#         volumes:
#             - postgres_data:/var/lib/postgresql/data/
#         environment:
#             - POSTGRES_DB=${DATABASE_NAME}
#             - POSTGRES_USER=${DATABASE_USER}
#             - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
# volumes:
#     postgres_data:
